
# INF28: ¿Cuál fue la fecha de instalación de un elemento urbano?

PREFIX edintinf: <http://vocab.linkeddata.es/datosabiertos/def/urbanismo-infraestructuras/infraestructura#>
PREFIX rdfs:     <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?element ?elementLabel
       ?installationDate
WHERE {

    # Sustituir por la URI del elemento urbano
    BIND(<URI-del-elemento-urbano> AS ?element)

    # Debe ser un UrbanElement
    ?element a edintinf:UrbanElement .

    OPTIONAL { ?element rdfs:label ?elementLabel . }

    # Fecha de instalación
    OPTIONAL { ?element edintinf:installationDate ?installationDate . }
}

#Para mantenimiento

PREFIX edintinf: <http://vocab.linkeddata.es/datosabiertos/def/urbanismo-infraestructuras/infraestructura#>
PREFIX rdfs:     <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?element ?elementLabel
       ?maintenanceDate
WHERE {

    # Sustituye este valor por la URI concreta del elemento urbano
    BIND(<URI-del-elemento-urbano> AS ?element)

    # Debe ser un UrbanElement
    ?element a edintinf:UrbanElement .

    OPTIONAL { ?element rdfs:label ?elementLabel . }

    # Fecha de mantenimiento
    OPTIONAL { ?element edintinf:maintenanceDate ?maintenanceDate . }
}